// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Z-8MhrMV6i4PCVqm4mEiFVOMUFRHcM8',
    appId: '1:96130726322:web:3fd91ff5524f5f5e1d4cab',
    messagingSenderId: '96130726322',
    projectId: 'kavini-e7d88',
    authDomain: 'kavini-e7d88.firebaseapp.com',
    databaseURL: 'https://kavini-e7d88-default-rtdb.firebaseio.com',
    storageBucket: 'kavini-e7d88.appspot.com',
    measurementId: 'G-LCKT9S7KWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByy8pIDR2PUO4I3nTfwCQ__dvTjBvExV8',
    appId: '1:96130726322:android:c1e5185ac95216111d4cab',
    messagingSenderId: '96130726322',
    projectId: 'kavini-e7d88',
    databaseURL: 'https://kavini-e7d88-default-rtdb.firebaseio.com',
    storageBucket: 'kavini-e7d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeV1964l-KvfIWUnDHLzrHp2j_4Xmstck',
    appId: '1:96130726322:ios:2aeb9053027242311d4cab',
    messagingSenderId: '96130726322',
    projectId: 'kavini-e7d88',
    databaseURL: 'https://kavini-e7d88-default-rtdb.firebaseio.com',
    storageBucket: 'kavini-e7d88.appspot.com',
    iosClientId: '96130726322-842ldsou2ds62lbhn86v6c4fgv7h1nk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavinie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeV1964l-KvfIWUnDHLzrHp2j_4Xmstck',
    appId: '1:96130726322:ios:2aeb9053027242311d4cab',
    messagingSenderId: '96130726322',
    projectId: 'kavini-e7d88',
    databaseURL: 'https://kavini-e7d88-default-rtdb.firebaseio.com',
    storageBucket: 'kavini-e7d88.appspot.com',
    iosClientId: '96130726322-842ldsou2ds62lbhn86v6c4fgv7h1nk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavinie',
  );
}
