// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGjkaVw4KcsPB-RxAQmfVncso0owIfmc',
    appId: '1:477903102861:web:3ec7f26f8500bf899b93c4',
    messagingSenderId: '477903102861',
    projectId: 'kavinie',
    authDomain: 'kavinie.firebaseapp.com',
    databaseURL: 'https://kavinie-default-rtdb.firebaseio.com',
    storageBucket: 'kavinie.appspot.com',
    measurementId: 'G-0D8KWM7XJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDapKnm0LD7irqtY1jGZVrL5_aWN6eLJT4',
    appId: '1:477903102861:android:1dc7e15f1a8617459b93c4',
    messagingSenderId: '477903102861',
    projectId: 'kavinie',
    databaseURL: 'https://kavinie-default-rtdb.firebaseio.com',
    storageBucket: 'kavinie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb00_0E4WEfzPrX43KHCTe11gIuED7ip0',
    appId: '1:477903102861:ios:3fe4bfaeeef0fa749b93c4',
    messagingSenderId: '477903102861',
    projectId: 'kavinie',
    databaseURL: 'https://kavinie-default-rtdb.firebaseio.com',
    storageBucket: 'kavinie.appspot.com',
    iosClientId: '477903102861-o3pp8vdj713k7hdnol7epod314hffccq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavinie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb00_0E4WEfzPrX43KHCTe11gIuED7ip0',
    appId: '1:477903102861:ios:3fe4bfaeeef0fa749b93c4',
    messagingSenderId: '477903102861',
    projectId: 'kavinie',
    databaseURL: 'https://kavinie-default-rtdb.firebaseio.com',
    storageBucket: 'kavinie.appspot.com',
    iosClientId: '477903102861-o3pp8vdj713k7hdnol7epod314hffccq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavinie',
  );
}
